<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.mathe-jung-alt</groupId>
    <artifactId>matheportal-shell</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>quarkus</packaging>

    <properties>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.37.2</quarkus.platform.version>

        <matheportal-bom.version>0.0.2-SNAPSHOT</matheportal-bom.version>
        <egladil-secure-tokens.version>1.0.0</egladil-secure-tokens.version>
        <auth-session.version>0.0.1-SNAPSHOT</auth-session.version>

        <mixin-maven-plugin.version>1.0.6</mixin-maven-plugin.version>
        <egladil-maven-mixins.version>2.0.0</egladil-maven-mixins.version>

        <!-- Start mixin-properties -->
        <pmd.failOnViolation>true</pmd.failOnViolation>
        <spotbugs.failOnError>true</spotbugs.failOnError>

        <jacoco.exclusion-1>de/mathejungalt/matheportal/shell/domain/generated/**</jacoco.exclusion-1>
        <jacoco.exclusion-2>de/mathejungalt/matheportal/shell/infrastructure/generated/**</jacoco.exclusion-2>

        <pmd-exclusion-1>**/generated-sources/**</pmd-exclusion-1>
        <!-- Ende mixin-propetries -->

        <openapi-generator-maven-plugin.version>7.20.0</openapi-generator-maven-plugin.version>

        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.parameters>true</maven.compiler.parameters>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>de.mathe-jung-alt</groupId>
                <artifactId>matheportal-bom</artifactId>
                <version>${matheportal-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>de.egladil.web</groupId>
            <artifactId>egladil-secure-tokens</artifactId>
        </dependency>

        <dependency>
            <groupId>de.mathe-jung-alt</groupId>
            <artifactId>auth-session</artifactId>
            <version>${auth-session.version}</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-routes</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mariadb</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway</artifactId>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.slf4j</groupId>
            <artifactId>slf4j-jboss-logmanager</artifactId>
        </dependency>


        <!-- test scoped -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-security</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jacoco</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>application.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>application.properties</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <groupId>com.playtika.maven.plugins</groupId>
                <artifactId>mixin-maven-plugin</artifactId>
                <version>${mixin-maven-plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <mixins>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-core-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-linting-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-code-quality-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-unittest-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-quarkustest-coverage-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                        <mixin>
                            <groupId>de.egladil</groupId>
                            <artifactId>java-security-mixin</artifactId>
                            <version>${egladil-maven-mixins.version}</version>
                        </mixin>
                    </mixins>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-internal-server-stubs</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/openapi/openapi.yaml</inputSpec>
                            <generatorName>jaxrs-spec</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <library>quarkus</library>
                                <useJakartaEe>true</useJakartaEe>
                                <useBeanValidation>true</useBeanValidation>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <interfaceOnly>true</interfaceOnly>
                                <returnResponse>true</returnResponse>
                                <useTags>true</useTags>
                                <sourceFolder>src/main/java</sourceFolder>
                                <basePackage>de.mathejungalt.matheportal.shell</basePackage>
                                <apiPackage>
                                    de.mathejungalt.matheportal.shell.infrastructure.generated</apiPackage>
                                <modelPackage>de.mathejungalt.matheportal.shell.domain.generated</modelPackage>
                                <generateConstructors>false</generateConstructors>
                                <generateBuilders>false</generateBuilders>
                                <openApiNullable>false</openApiNullable>
                                <generatedAnnotation>jakarta.annotation.Generated</generatedAnnotation>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>