#!/usr/bin/env bash

set -euo pipefail

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED_FILES" ]; then
  echo "No staged files."
  exit 0
fi

echo "Running cleanup on affected projects..."

pnpm nx affected -t cleanup --files="$STAGED_FILES"

git add $STAGED_FILES