quarkus.http.port=9102
quarkus.http.test-port=9102

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://mathe-jung-alt.de
quarkus.http.cors.access-control-allow-credentials=true

# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.sessions.db-kind=mariadb
quarkus.datasource.sessions.jdbc.url=jdbc:mariadb://matheportal-sessions-db:3306/matheportal_sessions
quarkus.datasource.sessions.username=matheportal_sessions

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.database.generation=none
quarkus.hibernate-orm.sessions.packages=de.mathejungalt.authsessions.internal.session.entities
