openapi: '3.0.3'
info:
    title: minikaenguru-anwendung API
    version: 1.0.0
    description: API der minikaenguru-anwendung.
paths:
    /api/berechtigungen:
        get:
            tags:
                - Berechtigungen
            summary: Läd die Minkänguru- Berechtigung eines eingeloggten Users
            description: >
                Holt die UUID aus der Session selektiert mit dieser den Wettbewerbsdurchführenden.
                Falls es einen gibt, wird die Session um eine Berechtigung erweitert und der
                zugehörige User wird zurückgegeben
            operationId: loadBerechtigung
            security:
                - mpSession: []
            responses:
                '200':
                    description: Zuordnung gefunden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '401':
                    description: Keine gültige Session vorhanden oder Session ist endgültig abgelaufen
                '404':
                    description: keine Zuordnung gefunden
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/wettbewerbsdurchfuehrende/konto:
        get:
            tags:
                - Wettbewerbsdurchfuehrender
            summary: 'Lesen eines Wettbewerbsdurchführenden'
            description: 'Ein Wettbewerbsdurchführender mit der uuid aus der session wird gelesen'
            operationId: loadWettbewerbsdurchfuehrenden
            security:
                - mpSession: []
            responses:
                '200':
                    description: Wettbewerbsdurchführender erfolgreich geladen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Wettbewerbsdurchfuehrender'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
        post:
            tags:
                - Wettbewerbsdurchfuehrender
            summary: 'Anlegen eines Wettbewerbsdurchführenden'
            description: 'Ein neuer Wettbewerbsdurchführender mit der uuid aus der session wird angelegt'
            operationId: createWettbewerbsdurchfuehrenden
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/WettbewerbsdurchfuerenderRequest'
            security:
                - mpSession: []
            responses:
                '201':
                    description: Wettbewerbsdurchführender erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Wettbewerbsdurchfuehrender'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
        put:
            tags:
                - Wettbewerbsdurchfuehrender
            summary: 'Ändern eines Wettbewerbsdurchführenden'
            description: 'Der Wettbewerbsdurchführende mit der uuid aus der session wird geändert'
            operationId: updateWettbewerbsdurchfuehrenden
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/WettbewerbsdurchfuerenderRequest'
            security:
                - mpSession: []
            responses:
                '201':
                    description: Wettbewerbsdurchführender erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Wettbewerbsdurchfuehrender'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
components:
    securitySchemes:
        mpSession:
            type: apiKey
            in: cookie
            name: MPSESSIONID
            description: Session-Cookie der Matheportal-Sitzung
    schemas:
        Wettbewerbsdurchfuehrungsart:
            type: string
            enum:
                - SCHULE
                - PRIVAT
            description: die Art, wie der Wettbewerb durchgeführt wird (als Schule oder privat)
            example:
                - SCHULE
                - PRIVAT
        ZugangsberechtigungUnterlagen:
            type: string
            enum:
                - STANDARD
                - ERTEILT
                - ENTZOGEN
            description: Das Herunterladen von Unterlagen kann außerhalb des Zeitfensters freigegeben oder innerhalb des Zeitfensters entzogen werden.
            example:
                - STANDARD
                - ERTEILT
                - ENTZOGEN
        WettbewerbsdurchfuerenderRequest:
            type: object
            required:
                - typ
            description: Requestobjekt für das Anlegen oder Ändern eines Wettbewerbsdurchführenden.
            properties:
                durchfuehrungsart:
                    type: object
                    $ref: '#/components/schemas/Wettbewerbsdurchfuehrungsart'
                schule:
                    type: string
                    description: Kürzel der Schule. Für die Durchführungsart SCHULE erforderlich.
        Wettbewerbsdurchfuehrender:
            type: object
            description: Responsobjekt für das Anlegen, Ändern und Laden eines bestimmten Wettbewerbsdurchführenden.
            properties:
                durchfuehrungsart:
                    type: object
                    $ref: '#/components/schemas/Wettbewerbsdurchfuehrungsart'
                teilnahmenummern:
                    type: array
                    uniqueItems: true
                    description: Teilnahmenummern sind bei Lehrpersonen die Schulkürzel, bei Privatpersonen ein eindeutiges 10stelliges Kürzel.
                    items:
                        type: string
                        pattern: '^[A-Z0-9]*$'
                    example:
                        - V8DDP4X9ZY
                        - SSBXQUBN
                newsletter:
                    type: boolean
                    description: Flag, ob der Durchführende Newsletter erhalten möchte
                zugangsberechtigungUnterlagen:
                    type: object
                    $ref: '#/components/schemas/ZugangsberechtigungUnterlagen'
        User:
            type: object
            required:
                - fullName
                - berechtigungen
            properties:
                fullName:
                    type: string
                    minLength: 1
                    maxLength: 201
                    pattern: "^[\\p{IsLatin}\\d]+(?:[ '\\-.’][\\p{IsLatin}\\d]+)*$"
                    description: Vollständiger Anzeigename (lateinische Buchstaben, Ziffern, Leerzeichen, Bindestrich, Apostroph)
                    example: María del Carmen 2
                berechtigungen:
                    type: array
                    uniqueItems: true
                    description: Berechtigungen des Benutzers. Diese werden im gegebenen Kontext aus IAM und den 2 Berechtigungstypen Minikänguru gemerged
                    items:
                        type: string
                        pattern: '^[A-Z]+(_[A-Z]+)*$'
                    example:
                        - STANDARD
                        - ADMIN
                        - SCHULE
                        - PRIVAT
                        - AUTOR
        ConstraintViolationDetail:
            type: object
            properties:
                field:
                    type: string
                    description: Feldname der verletzten Constraint.
                    example: clientId
                message:
                    type: string
                    description: Fehlermeldung zur verletzten Constraint.
                    example: clientId ist ungueltig.
        ErrorResponse:
            type: object
            required:
                - message
            properties:
                message:
                    type: string
                    example: Irgendein Fehler ist aufgetreten
                connstraintViolations:
                    type: array
                    items:
                        $ref: '#/components/schemas/ConstraintViolationDetail'
