# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://mk-wettbewerb-database:3306/minikaenguru
quarkus.datasource.username=minikaenguru

# Flyway Configuration
quarkus.flyway.connect-retries=2
quarkus.flyway.default-schema=minikaenguru
quarkus.flyway.table=schema_version
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-disabled=true
quarkus.flyway.create-schemas=false
quarkus.flyway.validate-migration-naming=true
