quarkus.http.port=9100

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://mathe-jung-alt.de
quarkus.http.cors.access-control-allow-credentials=true

# --------------------------------------------------------------------------------
#           Authentifizierung
# --------------------------------------------------------------------------------
auth-app.url=https://mathe-jung-alt.de/authprovider/
public-redirect-url=https://mathe-jung-alt.de/matheportal/

# Issuer-Prüfung (entspricht withIssuer(...))
mp.jwt.verify.issuer=heike2718/authprovider

mp.jwt.verify.publickey.location=keys/authprov_public_key.pem

# Optional: etwas Toleranz bei Uhrzeiten (Sekunden)
smallrye.jwt.verify.clock.skew=5

# --------------------------------------------------------------------------------
#           REST-Clients
# --------------------------------------------------------------------------------
## authprovider
quarkus.rest-client.authprovider.url=https://mathe-jung-alt.de/authprovider
quarkus.rest-client.authprovider.scope=ApplicationScoped
quarkus.rest-client.authprovider.connect-timeout=5000
quarkus.rest-client.authprovider.read-timeout=30000

# diagnose bei Fehlern - mal ins payload schauen
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=5000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=ERROR

# --------------------------------------------------------------------------------
#           CDI
# --------------------------------------------------------------------------------
quarkus.index-dependency.authsessions.group-id=de.mathejungalt
quarkus.index-dependency.authsessions.artifact-id=authsessions


# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.sessions.db-kind=mariadb
quarkus.datasource.sessions.jdbc.url=jdbc:mariadb://matheportal-sessions-db:3306/matheportal_sessions
quarkus.datasource.sessions.username=matheportal_sessions_user

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.database.generation=none

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.packages=de.mathejungalt.authsessions.internal.session.entities


%test.client.id=matheportalShellClient
