openapi: '3.0.3'
info:
    title: minikaenguru-admin API
    version: 1.0.0
    description: API für minikaenguru-admin.
paths:
    /api/schulkatalog/laender:
        get:
            tags:
                - Schulkatalog
            summary: 'Laden der Länder des Schulkatalogs'
            description: 'alle Länder des Schulkatalogs werden geladen'
            operationId: loadLaender
            security:
                - mpSession: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Land'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/schulkatalog/laender/{kuerzelLand}/orte:
        get:
            tags:
                - Schulkatalog
            summary: 'Laden von Orten des Schulkatalogs'
            description: 'alle Orte eines Landes des Schulkatalogs werden geladen'
            operationId: loadOrte
            security:
                - mpSession: []
            parameters:
                - in: path
                  name: kuerzelLand
                  schema:
                      type: string
                      pattern: '^[A-Z-]*$'
                      maxLength: 5
                  required: true
                  description: kuerzel des Landes
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Ort'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/schulkatalog/orte/{kuerzelOrt}/schulen:
        parameters:
            - in: path
              name: kuerzelOrt
              schema:
                  type: string
                  pattern: '^[A-Z0-9]*$'
                  maxLength: 8
              required: true
              description: kuerzel des Ortes
        get:
            tags:
                - Schulkatalog
            summary: Laden von Schulen des Schulkatalogs
            description: alle Schulen eines Ortes des Schulkatalogs werden geladen
            operationId: loadSchulen
            security:
                - mpSession: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Schule'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
        post:
            tags:
                - Schulkatalog
            summary: neue Schule in einem Ort
            description: neue Schule wird angelegt
            operationId: schuleInOrtAnlegen
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SchuleAnlegenOderAendernRequest'
            responses:
                '201':
                    description: Schule erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Schulkuerzel'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: land existiert nicht
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/schulkatalog/schulen:
        post:
            tags:
                - Schulkatalog
            summary: neue Schule
            description: Land, Ort und Schule werden angelegt
            operationId: schuleAnlegen
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LandMitOrtUndSchuleAnlegenRequest'
            security:
                - mpSession: []
            responses:
                '201':
                    description: Schule erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Schulkuerzel'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/schulkatalog/laender/{kuerzelLand}/schulen:
        post:
            tags:
                - Schulkatalog
            summary: neue Schule in einem Land / Bundesland
            description: Ort und Schule werden angelegt
            operationId: schuleInLandAnlegen
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/OrtMitSchuleAnlegenRequest'
            security:
                - mpSession: []
            parameters:
                - in: path
                  name: kuerzelLand
                  schema:
                      type: string
                      pattern: '^[A-Z-]*$'
                      maxLength: 5
                  required: true
                  description: kuerzel des Landes
            responses:
                '201':
                    description: Schule erfolgreich angelegt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Schulkuerzel'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: land existiert nicht
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
    /api/schulkatalog/schulen/{kuerzel}:
        put:
            tags:
                - Schulkatalog
            summary: Schule umbenennen
            description: die gegebene Schule wird umbenannt
            operationId: schuleUmbenennen
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SchuleAnlegenOderAendernRequest'
            security:
                - mpSession: []
            parameters:
                - in: path
                  name: kuerzel
                  schema:
                      type: string
                      pattern: '^[A-Z0-9]*$'
                      maxLength: 8
                  required: true
                  description: kuerzel der Schule
            responses:
                '200':
                    description: Schule erfolgreich umbenannt
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Schulkuerzel'
                '400':
                    description: Request ist ungültig
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: keine Session oder Session abgelaufen
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: nicht autorisiert
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: land existiert nicht
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    description: Serverfehler
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
components:
    securitySchemes:
        mpSession:
            type: apiKey
            in: cookie
            name: MPSESSIONID
            description: Session-Cookie der Matheportal-Sitzung
    schemas:
        ConstraintViolationDetail:
            type: object
            required:
                - field
                - message
            properties:
                field:
                    type: string
                    description: Feldname der verletzten Constraint.
                    example: clientId
                message:
                    type: string
                    description: Fehlermeldung zur verletzten Constraint.
                    example: clientId ist ungueltig.
        ErrorResponse:
            type: object
            required:
                - message
            properties:
                message:
                    type: string
                    example: Irgendein Fehler ist aufgetreten
                constraintViolations:
                    type: array
                    items:
                        $ref: '#/components/schemas/ConstraintViolationDetail'
        Land:
            type: object
            required:
                - kuerzel
                - name
                - anzahlOrte
            properties:
                kuerzel:
                    type: string
                    pattern: '^[A-Z\-]*$'
                    maxLength: 5
                name:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                anzahlOrte:
                    type: integer
        Ort:
            type: object
            required:
                - land
                - kuerzel
                - name
                - anzahlSchulen
            properties:
                land:
                    $ref: '#/components/schemas/Land'
                kuerzel:
                    type: string
                    pattern: '^[A-Z0-9]*$'
                    maxLength: 8
                name:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                anzahlSchulen:
                    type: integer
        Schule:
            type: object
            required:
                - ort
                - kuerzel
                - name
            properties:
                ort:
                    $ref: '#/components/schemas/Ort'
                kuerzel:
                    type: string
                    pattern: '^[A-Z0-9]*$'
                    maxLength: 8
                name:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
        SchuleAnlegenOderAendernRequest:
            type: object
            required:
                - name
                - emailAuftraggeber
            properties:
                name:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                emailAuftraggeber:
                    type: string
                    pattern: '^[^\s@]+@[^\s@]+\.[^\s@]+$'
                    maxLength: 255
        OrtMitSchuleAnlegenRequest:
            type: object
            required:
                - nameOrt
                - nameSchule
                - emailAuftraggeber
            properties:
                nameOrt:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                nameSchule:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                emailAuftraggeber:
                    type: string
                    pattern: '^[^\s@]+@[^\s@]+\.[^\s@]+$'
                    maxLength: 255
        LandMitOrtUndSchuleAnlegenRequest:
            type: object
            required:
                - kuerzelLand
                - nameLand
                - nameOrt
                - nameSchule
                - emailAuftraggeber
            properties:
                kuerzelLand:
                    type: string
                    pattern: '^[A-Z\-]*$'
                    maxLength: 5
                nameLand:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                nameOrt:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                nameSchule:
                    type: string
                    pattern: '^[\p{sc=Latin}\p{M}\p{N}\p{P}\p{S}\p{Zs}]*$'
                    maxLength: 100
                emailAuftraggeber:
                    type: string
                    pattern: '^[^\s@]+@[^\s@]+\.[^\s@]+$'
                    maxLength: 255
        Schulkuerzel:
            type: object
            required:
                - kuerzel
            properties:
                kuerzel:
                    type: string
                    pattern: '^[A-Z0-9]*$'
                    maxLength: 8
