quarkus.http.port=9104

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://mathe-jung-alt.de
quarkus.http.cors.access-control-allow-credentials=true

# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.sessions.db-kind=mariadb
quarkus.datasource.sessions.jdbc.url=jdbc:mariadb://matheportal-sessions-db:3306/matheportal_sessions
quarkus.datasource.sessions.username=matheportal_sessions

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.database.generation=none
quarkus.hibernate-orm.sessions.packages=de.mathejungalt.authsessions.internal.session.entities

quarkus.datasource.minikaenguru.db-kind=mariadb
quarkus.datasource.minikaenguru.jdbc.url=jdbc:mariadb://mk-wettbewerb-database:3306/minikaenguru
quarkus.datasource.minikaenguru.username=minikaenguru

quarkus.hibernate-orm.minikaenguru.datasource=minikaenguru
quarkus.hibernate-orm.minikaenguru.database.generation=none
quarkus.hibernate-orm.minikaenguru.packages=de.mathejungalt.minikaenguru.admin.infrastructure.persistence.entities
