quarkus.http.port=9104

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://mathe-jung-alt.de
quarkus.http.cors.access-control-allow-credentials=true

# --------------------------------------------------------------------------------
#          Serialization
# --------------------------------------------------------------------------------
# see https://quarkus.io/guides/rest#accessing-request-parameters
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true


# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.sessions.db-kind=mariadb
quarkus.datasource.sessions.jdbc.url=jdbc:mariadb://matheportal-sessions-db:3306/matheportal_sessions
quarkus.datasource.sessions.username=matheportal_sessions

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.database.generation=none
quarkus.hibernate-orm.sessions.packages=de.mathejungalt.authsessions.internal.session.entities

quarkus.datasource.minikaenguru.db-kind=mariadb
quarkus.datasource.minikaenguru.jdbc.url=jdbc:mariadb://mk-wettbewerb-database:3306/minikaenguru
quarkus.datasource.minikaenguru.username=minikaenguru

quarkus.hibernate-orm.minikaenguru.datasource=minikaenguru
quarkus.hibernate-orm.minikaenguru.database.generation=none
quarkus.hibernate-orm.minikaenguru.packages=de.mathejungalt.minikaenguru.admin.infrastructure.persistence.entities

# --------------------------------------------------------------------------------
#           Logging
# --------------------------------------------------------------------------------
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %p (%t) clientId=%X{clientId}, correlationId=%X{correlationId}, [%c:%L] %s%e%n
quarkus.log.level=INFO

quarkus.log.file.enabled=true
quarkus.log.file.level=INFO
quarkus.log.file.path=/deployments/logs/server.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %p (%t) clientId=%X{clientId}, correlationId=%X{correlationId}, [%c:%L] %s%e%n
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd

quarkus.http.access-log.enabled=true
quarkus.http.record-request-start-time=true
quarkus.http.access-log.pattern=%h %l %u [%t] "%r" %s %b "%{i,Referer}" "%{i,User-Agent}" %D "%{i,X-CLIENT-ID}" "%{i,X-CORRELATION-ID}"
quarkus.http.access-log.log-to-file=true
quarkus.http.access-log.base-file-name=access
quarkus.http.access-log.log-directory=/deployments/logs
quarkus.http.access-log.rotate=true
