quarkus.http.port=9101


quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://mathe-jung-alt.de
quarkus.http.cors.access-control-allow-credentials=true


# --------------------------------------------------------------------------------
#           Session-Timeouts
# --------------------------------------------------------------------------------
session.idle.timeout=60
session.max.lifetime=1440


# --------------------------------------------------------------------------------
#           database
# --------------------------------------------------------------------------------
quarkus.datasource.sessions.db-kind=mariadb
quarkus.datasource.sessions.jdbc.url=jdbc:mariadb://matheportal-sessions-db:3306/matheportal_sessions
quarkus.datasource.sessions.username=matheportal_sessions_user

quarkus.hibernate-orm.sessions.datasource=sessions
quarkus.hibernate-orm.sessions.database.generation=none
quarkus.hibernate-orm.sessions.packages=de.mathejungalt.authsessions.internal.session.entities
